### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/3ac512e5-5f4d-11ef-bc28-18c04d8e554c

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=ACTION

### Crear una película con POST 
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Iron Man 3",
    "year": 2013,
    "director": "Shane Black",
    "duration": 131,
    "poster": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/1f/Iron_Man_3_Portada.png/revision/latest?cb=20191029194857&path-prefix=es",
    "genre": [
        "actioN",
        "DrAma",
        "Crime"    
    ]
}

### Borrar una película 
DELETE http://localhost:1234/movies/3ad75536-5f4d-11ef-bc28-18c04d8e554c

### Actualizar una pelicula( Uno o varios paramaetros del objeto de la pelicula con el PATCH)

PATCH http://localhost:1234/movies/3ac512e5-5f4d-11ef-bc28-18c04d8e554c
Content-Type: application/json

{
    "title": "2121",
    "year": 2024

}


